### ISSUE TITLE
[1.16.4] [Mod Interaction] Forbidden & Arcanus Eternal Stella can repair tome

### ISSUE THREAD

**Issue by jeremiahwinsley** [bl4ckscor3/XP-Tome#11]
With Forbidden & Arcanus, the Eternal Stella can be applied to the XP Tome. This repairs it automatically, allowing for unlimited XP gain.

**Comment by bl4ckscor3** [comment]
I would say that this is a bug with Forbidden & Arcanus, because they should check whether an item is repairable or not - and the XP Tome isn't.

However I'm working on a rewrite of XP Tome, that will allow for configuration options, and will automatically fix this issue, because XP storage will no longer be based on damage values.

**Comment by bl4ckscor3** [comment]
Closed by 14c8c87d0f3871ec498ac0dcedf632c7fc8775de.
