### ISSUE TITLE
No Config - Sad face :-(

### ISSUE THREAD

**Issue by sjonesuk** [bl4ckscor3/XP-Tome#25]
Hi,

I have always updated the config on your mod to allow for max level storage due to Apothiosis etc however in the latest version there is no config. I am using version xptome-1.21-2.3.2.jar.  Minecraft 1.21.1 NeoForge. 

Is this something you are aware of?

Thanks

Steve

**Comment by bl4ckscor3** [comment]
Yes, it was an intentional change during the port to Minecraft 1.20.5, where I moved all the config settings to the new data component system. Each XP Tome item can now be configured individually instead of the config affecting all of them at once. By overriding the XP Tome's recipe using a datapack, the settings can be changed for newly crafted XP Tomes.

**Comment by sjonesuk** [comment]
Ok, thanks for responding. I dont see anything in the datapacks folder or am I looking in the wrong place?

**Comment by bl4ckscor3** [comment]
You need to create a datapack with the new recipe yourself which you then place into the datapacks folder in order for it to be recognized by the game. More info:
https://minecraft.wiki/w/Data_pack
https://minecraft.wiki/w/Recipe

**Comment by sjonesuk** [comment]
Again,  much appreciate your response.  Maybe, add one there already when the Mod is loaded first time, as the Curseforge description doesnt give an adequate expaination of what meta data should be in the datapack and/or the format for it.
